### ISSUE TITLE
All pages problem

### ISSUE THREAD

**Issue by irwinx16** [irwinx16/portfolio-2.0#1]
- About page -The picture I used with the imp-fluid, it looks fine on md but when it goes large, the image goes way to big for the page and the text.

- Projects page - I used the sticky footer but on this page, the last project's buttons are hidden behind the footer.

- Home page - I used those animation cause it was just copy and paste. I like in md and lg, but when it goes small I don't how how to make it split in two rows instead of my last name being cut like that.

Thank you.

**Comment by richardcornish** [comment]
@irwinx16 Next time, break these out one at a time. This should be three issues.
